version: '3.8'
services:
  apollo-server:
    build: .
    ports:
      - "3000:3000"
    command: ["npm", "run", "start-server"]
    volumes:
      - ./app:/app
    depends_on:
      - es

  web-server:
    build: .
    ports:
      - "3030:3030"
    command: ["npm", "run", "start-client"]
    volumes:
      - ./app:/app
    depends_on:
      - es

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

volumes:
  esdata1:
    driver: local
